services:
  notif:
    build:
      context: .
      dockerfile: Dockerfile
    image: myges-grades-notifications:latest
    container_name: myges-grades-notifications
    restart: always
    volumes:
      - not-vol:/app

volumes:
  not-vol: